### ISSUE TITLE
Data class implements RealmModel instead of extending RealmObject

### ISSUE THREAD

**Issue by WojciechCz** [PhilJay/MPAndroidChart-Realm#4]
Hey

I was just about to use this library and was very excited about integration with Realm but in my project my data classes don't extend **RealmObject** class. Instead of that I simple implement [RealmModel](https://realm.io/docs/java/latest/#realmmodel-interface) interface. This solution is more flexible:

```
@RealmClass
public class User implements RealmModel {

}
```

Do you plan to support **RealmModel** in future releases?

Cheers
W

**Comment by PhilJay** [comment]
Yes, I will support this in the next release!

**Comment by PhilJay** [comment]
Out now!
