### ISSUE TITLE
Support for RealmList?

### ISSUE THREAD

**Issue by casidiablo** [PhilJay/MPAndroidChart-Realm#7]
There are cases in it's useful to chart datasets in one-to-many relationships. In that case we have a `RealmList` instead of a `RealmResult`.

It'd be great if it was supported natively.

**Comment by valentinstoqnov** [comment]
In order to transform RealmList to RealmResults you just have to call where() on your RealmList and then findAll(). Example : yourObject.getRealmList().where().findAll()
