### ISSUE TITLE
Please implement example app

### ISSUE THREAD

**Issue by takahirom** [PhilJay/MPAndroidChart-Realm#9]
I want to learn how it work from the example.
https://github.com/PhilJay/MPAndroidChart-Realm/blob/master/MPChartExample-Realm/src/main/java/com/github/mikephil/charting/realm/MainActivity.java

**Comment by PhilJay** [comment]
https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/realm

**Comment by DarisMathew** [comment]
> https://github.com/PhilJay/MPAndroidChart/tree/master/MPChartExample/src/com/xxmassdeveloper/mpchartexample/realm

This link is currently not working!!!
